version: '3'

networks:
  babyson_shop:
  database_desktop:
    external:
      name: database_desktop

services:
  web:
    build: ./web
    volumes:
      - ./www:/var/www/html
      - ./web/php.ini:/usr/local/etc/php/php.ini
    networks:
      - babyson_shop
      - database_desktop

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - babyson_shop
volumes:
  www:
